# Generated by Django 5.1.5 on 2025-01-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_persona', models.CharField(choices=[('N', 'Natural'), ('J', 'Jurídica')], max_length=1)),
                ('numero_identificacion', models.CharField(max_length=20, unique=True)),
                ('tipo_identificacion', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('NIT', 'Número de Identificación Tributaria'), ('TI', 'Tarjeta de Identidad')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('U', 'Urbano'), ('R', 'Rural')], max_length=1)),
                ('numero_catastral', models.CharField(max_length=30, unique=True)),
                ('numero_matricula', models.CharField(max_length=50, unique=True)),
                ('propietarios', models.ManyToManyField(to='predios.propietario')),
            ],
        ),
    ]
